api/urls.py
from django.urls import path

from api import views

app_name = "api"
urlpatterns = [
    path(
        "channel/",
        views.ChannelListAPIView.as_view(),
        name="channel-list",
    ),
    path(
        "channel/<uuid:uuid>/",
        views.ChannelRetrieveAPIView.as_view(),
        name="channel-detail",
    ),
    path(
        "content/",
        views.ContentListAPIView.as_view(),
        name="content-list",
    ),
    path(
        "content/<uuid:uuid>/",
        views.ContentRetrieveAPIView.as_view(),
        name="content-detail",
    ),
]

immfly/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from immfly.views import ChannelView, ContentDetail, ContentView

admin.site.site_header = settings.SITE_HEADER
admin.site.site_title = settings.SITE_HEADER

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/", include("api.urls")),
    path("", ChannelView.as_view(), name="channel"),
    path("content/", ContentView.as_view(), name="content"),
    path("content-detail/", ContentDetail.as_view(), name="content-detail"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
import uuid

from django.db import models
from django.utils.translation import ugettext_lazy as _

from api.managers import ChannelManager, ContentManager


class TimestampedModel(models.Model):
    uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        unique=True,
        verbose_name=_("Uuid"),
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Created at"),
    )
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name=_("Updated at"),
    )

    class Meta:
        abstract = True


class Group(TimestampedModel):
    class Meta:
        ordering = ["-created"]
        verbose_name = _("Group")
        verbose_name_plural = _("Groups")

    name = models.CharField(
        max_length=120,
        verbose_name=_("Group name"),
    )

    def __str__(self):
        return self.name


class Channel(TimestampedModel):
    class Meta:
        ordering = ["-created"]
        verbose_name = _("Channel")
        verbose_name_plural = _("Channels")

    title = models.CharField(
        max_length=120,
        verbose_name=_("Title"),
    )
    language = models.CharField(
        max_length=120,
        default="en",
        verbose_name=_("Language"),
    )
    picture = models.ImageField(
        upload_to="channel/",
        verbose_name=_("Picture"),
    )
    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        related_name="subchannels",
        on_delete=models.CASCADE,
        verbose_name=_("Parent"),
    )
    groups = models.ManyToManyField(
        Group,
        verbose_name=_("Groups"),
        blank=True,
    )

    objects = ChannelManager()

    def __str__(self):
        return self.title


class Content(TimestampedModel):
    class Meta:
        ordering = ["-created"]
        verbose_name = _("Content")
        verbose_name_plural = _("Contents")

    name = models.CharField(
        max_length=240,
        verbose_name=_("Name"),
    )
    metadata = models.JSONField(
        default=dict,
        blank=True,
        verbose_name=_("Metadata"),
    )
    rating = models.FloatField(
        default=0.0,
        verbose_name=_("Rating"),
    )
    channel = models.ForeignKey(
        Channel,
        related_name="contents",
        on_delete=models.CASCADE,
        verbose_name=_("Channel"),
    )
    file = models.FileField(
        upload_to="content/",
        verbose_name=_("File"),
    )

    objects = ContentManager()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if self.channel.subchannels.count():
            raise Exception("Channel is a parent channel, cannot add content!")
        super().save(*args, **kwargs)

api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView

from api.models import Channel, Content
from api.serializers import ChannelSerializer, ContentSerializer


class ChannelListAPIView(ListAPIView):
    serializer_class = ChannelSerializer
    lookup_field = "uuid"

    def get_queryset(self):
        parent = self.request.query_params.get("parent")
        group = self.request.query_params.get("group")
        return (
            Channel.objects.by(group=group, parent=parent)
            .select_related("parent")
            .prefetch_related("groups")
            .all()
        )


class ChannelRetrieveAPIView(RetrieveAPIView):
    serializer_class = ChannelSerializer
    lookup_field = "uuid"
    queryset = Channel.objects.all()


class ContentListAPIView(ListAPIView):
    serializer_class = ContentSerializer
    lookup_field = "uuid"

    def get_queryset(self):
        channel = self.request.query_params.get("channel")
        return (
            Content.objects.by(channel=channel)
            .select_related("channel")
            .prefetch_related("channel__groups")
            .all()
        )


class ContentRetrieveAPIView(RetrieveAPIView):
    serializer_class = ContentSerializer
    lookup_field = "uuid"
    queryset = Content.objects.all()

immfly/views.py
from django.views.generic import TemplateView


class ChannelView(TemplateView):
    template_name = "channel.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        parent = self.request.GET.get("parent") or ""
        context.update(parent=parent)
        return context


class ContentView(TemplateView):
    template_name = "content.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        channel = self.request.GET.get("channel") or ""
        context.update(channel=channel)
        return context


class ContentDetail(TemplateView):
    template_name = "content-detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        uuid = self.request.GET.get("uuid")
        context.update(uuid=uuid)
        return context

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'app/css/bootstrap.min.css' %}" rel="stylesheet">
    <title>Immfly!</title>
    {% block styles %}
    {% endblock %}
</head>
<body>
<div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <span class="fs-4">Immfly</span>
        </a>
        <ul class="nav nav-pills">
            <li class="nav-item"><a href="{% url 'channel' %}" class="nav-link">Home</a></li>
        </ul>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</div>


<script src="{% static 'app/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'app/js/axios.min.js' %}"></script>
<script src="{% static 'app/js/jquery-3.6.0.min.js' %}"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

templates/channel.html
{% extends "base.html" %}

{% block content %}
    <h1 class="mb-4 text-center" id="channelTitle">Channels</h1>
    <div class="row gy-4">
        <div class="col-12">
            <div class="input-group input-group-sm mb-3">
                <span class="input-group-text" id="inputGroup-sizing-sm">🔎</span>
                <input type="text" id="searchByGroup" class="form-control" placeholder="Search by group">
            </div>
        </div>
        <div class="col">
            <div class="list-group" id="channels">
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
      let loadingHtml = `
        <div class="d-flex justify-content-center">
          <div class="spinner-border text-danger" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
        </div>
        `;

      function setParent() {
        let elemTitle = $("#channelTitle");

        {% if parent %}
          let url = `{% url 'api:channel-detail' parent %}`;
          axios
            .get(url)
            .then(({data}) => {
              elemTitle.text(data.title)
            })
            .catch(err => elemTitle.text(err.toString()))
        {% endif %}
      }

      function getChannels(group = "") {
        let elemChannels = $("#channels");
        elemChannels.html(loadingHtml)

        let url = `{% url 'api:channel-list' %}?group=${group}&parent={{ parent }}`;

        axios
          .get(url)
          .then(({data}) => {
            let html = data.map(each => {
              let groups = each.groups.map(grp => `<span class="badge bg-primary">${grp.name}</span>`).join("")
              let nextUrl;
              if (each.type === "SUB") {
                nextUrl = `{% url 'channel' %}?parent=${each.uuid}`
              } else {
                nextUrl = `{% url 'content' %}?channel=${each.uuid}`
              }
              return `
              <a href="${nextUrl}" class="list-group-item list-group-item-action" aria-current="true">
                <img src="${each.picture}" alt="" width="100" height="100">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">${each.title}</h5>
                  <span class="badge bg-success rounded-pill">${groups}</span>
                </div>
                <small>${each.language}</small>
              </a>
              `
            }).join(" ")
            elemChannels.html(html)
          })
          .catch(err => elemChannels.html(err.toString()))

        setParent();
      }

      $("#searchByGroup").keypress((e) => {
        if (e.keyCode !== 13) return;
        getChannels(e.target.value)
      })

      getChannels()
    </script>
{% endblock %}

templates/content-detail.html
{% extends "base.html" %}

{% block content %}
    <h1 class="mb-4 text-center">Content Detail</h1>
    <div class="row gy-4">
        <div class="col" id="content">
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
      let loadingHtml = `
        <div class="d-flex justify-content-center">
          <div class="spinner-border text-danger" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
        </div>
        `;

      function getContent() {
        let elemContents = $("#content");
        elemContents.html(loadingHtml)

        let url = `{% url 'api:content-detail' uuid %}`;

        axios
          .get(url)
          .then(({data}) => {
            let metadata = ""
            for (let key in data.metadata) {
              if (data.metadata.hasOwnProperty(key)) {
                metadata += `<li class="list-group-item"><b>${key}:</b> ${data.metadata[key]}</li>`
              }
            }
            let html = `
                <div class="card" >
                  <div class="card-body">
                    <h5 class="card-title">${data.name}</h5>
                    <p class="card-text">${data.rating}/10</p>
                  </div>
                  <ul class="list-group list-group-flush">${metadata}</ul>
                  <div class="card-body">
                    <a href="${data.file}" class="card-link">File</a>
                  </div>
                </div>
              `
            elemContents.html(html)
          })
          .catch(err => elemContents.html(err.toString()))
      }

      getContent()
    </script>
{% endblock %}

templates/content.html
{% extends "base.html" %}

{% block content %}
    <h1 class="mb-4 text-center">Contents</h1>
    <div class="row gy-4">
        <div class="col">
            <div class="list-group" id="contents">
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
      let loadingHtml = `
        <div class="d-flex justify-content-center">
          <div class="spinner-border text-danger" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
        </div>
        `;

      function getContents() {
        let elemContents = $("#contents");
        elemContents.html(loadingHtml)

        let url = `{% url 'api:content-list' %}?channel={{ channel }}`;

        axios
          .get(url)
          .then(({data}) => {
            let html = data.map(each => {
              let nextUrl = `{% url 'content-detail' %}?uuid=${each.uuid}`
              return `
              <a href="${nextUrl}" class="list-group-item list-group-item-action" aria-current="true">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">${each.name}</h5>
                  <span class="badge bg-primary rounded-pill">${each.rating}/10</span>
                </div>
              </a>
              `
            }).join(" ")
            elemContents.html(html)
          })
          .catch(err => elemContents.html(err.toString()))
      }

      getContents()
    </script>
{% endblock %}